name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Test and Build
        run: |
          npm install
          npm run lint
          npx pretty-quick --check .

          npm run test
